// Code generated by irgen; DO NOT EDIT.

package intexpr

type Lit struct {
	N int
}
type Var struct {
	Name string
}
type Add struct {
	Left, Right Expr
}
type Sub struct {
	Left, Right Expr
}
type Mul struct {
	Left, Right Expr
}

func (Expr *Lit) FeedTo(consumer ExprConsumer) { consumer.Lit(Expr.N) }
func (Expr *Var) FeedTo(consumer ExprConsumer) { consumer.Var(Expr.Name) }
func (Expr *Add) FeedTo(consumer ExprConsumer) { consumer.Add(Expr.Left, Expr.Right) }
func (Expr *Sub) FeedTo(consumer ExprConsumer) { consumer.Sub(Expr.Left, Expr.Right) }
func (Expr *Mul) FeedTo(consumer ExprConsumer) { consumer.Mul(Expr.Left, Expr.Right) }
